version: "3"

services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"

    kafka:
        container_name: "ReactCart-Notifications-Service-Kafka"
        image: confluentinc/cp-kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        expose:
            - "29092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
            KAFKA_MIN_INSYNC_REPLICAS: "1"

    kafka-ui:
        container_name: "ReactCart-Notifications-Service-Kafka-UI"
        image: provectuslabs/kafka-ui
        ports:
            - 8084:8080
        environment:
            DYNAMIC_CONFIG_ENABLED: "true"

    app:
        container_name: ReactCart-Notifications-Service-App
        image: node:latest
        working_dir: /app
        volumes:
            - ./:/app
        command: ["npm build", "npm start"]
        ports:
            - "3000:3000"
        depends_on:
            - kafka
